### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by fjarri** [nucypher/rust-umbral#12]
Should the main package and its bindings have independent versioning, or should we just synchronize the versions for everything? The latter will make things easier for users, especially those using the library from several languages at once. But it will lead to some releases where absolutely nothing has changed except for the version of another binding.

**Comment by fjarri** [comment]
Another related thing - we might want to make the first stable version 0.2.0, to synchronize with PyUmbral 0.2.0 (which will be binary compatible).

**Comment by cygnusv** [comment]
What about 1.0?

**Comment by fjarri** [comment]
I would like v1.0 to include fully-functioning JS bindings and a fully stabilized API. I guess I'm just being on the safe side and want at least one beta release before that.

**Comment by cygnusv** [comment]
Understood. My reasoning for v1.0 was the fact that this is a major change (not only API, but the programming language and even some parts of the crypto itself). There's also the possibility of having a beta release, at least in the pypi side. Is that possible too in the rust PM?

**Comment by fjarri** [comment]
I think in SemVer when you're in the 0.x zone you are allowed to have breaking changes between minor versions, so I was planning to do that. In Rust, as it seems, people just use this convention and don't have beta releases per se - anything in 0.x is assumed to be beta.

**Comment by fjarri** [comment]
Final decision: we are synchronizing all versions of the main package and the bindings, and additionally synchronizing them with the `pyumbral` version as well.
