### ISSUE TITLE
Possibly reduce the amount of hash functions used in the code

### ISSUE THREAD

**Issue by fjarri** [nucypher/rust-umbral#2]
In the Python implementation we have, in different places, SHA256, Blake2b and Keccak. In this implementation some occurrences of Blake2b are replaced with SHA3 temporarily because of digest length requirements (e.g. in `hash_to_scalar()`). Could we use a single hash function everywhere?

**Comment by vepkenez** [comment]
After I spent so much time finding a useable and compatible blake2b library for JS 😢😢😢😢

**Comment by fjarri** [comment]
From the discussion: use SHA-256 everywhere. Seems like `unsafe_hash_to_point()` can use it as well.

**Comment by cygnusv** [comment]
To be clear, we will use SHA-256 "everywhere", but in some cases we can't use it directly; for example, when hashing to a scalar, where we will use a more complex construction which internally uses SHA256 (but no other hashing function).

After reading the [security discussion](https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-10.html#name-security-considerations-3) in the hash-to-curve standard, it's clear that SHA256 alone could introduce a small bias when used modulo `p` directly, so it needs to be "expanded". 

For the particular case of hashing to a scalar, we need to use the [`hash_to_field`](https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-10.html#name-hash_to_field-implementation) algorithm described in the standard. Internally, and for the particular combination of SHA256 and secp256k1, this uses a construction called [`expand_message_xmd`](https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-10.html#name-expand_message_xmd-2) which outputs 48-byte digests. See [here](https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-10.html#name-expand_message_xmdsha-256-2) some test vectors for `expand_message_xmd` instantiated with SHA256.

So, in essence, every time that we were using `hash_to_curvebn` in pyumbral, we would use now `hash_to_field` from the standard. Note that `hash_to_field` natively supports domain separation tags (#38), so we don't need to add them in an ad-hoc manner as we were doing in pyumbral.

**Comment by fjarri** [comment]
Hm, I'm confused here. `hash_to_field` is not an exact analogue of PyUmbral's `hash_to_curvebn`. The former hashes to the domain of curve coordinates, the latter to the domain of scalars. So they do the same thing, true, but security requirements may be different.

What was `hash_to_curvebn` in PyUmbral is now `ScalarDigest`, and uses `Scalar::from_digest()` from the backend library (`k256`), which is implemented as modulo reduction of the digest without expansion. Is that a potential problem? If it is, I would prefer to fix it in `k256` and not here (may not be even possible to fix it here if `k256` does not expose enough internals). 

If I understand the implementation of `hash_to_curvebn()` in PyUmbral, it does the same as what is done here:
- the DST is added just as another input to the digest
- the digest is taken modulo the order without any expansion

The only difference I noticed is that it is guaranteed to return a non-zero value. Is that important?
