### ISSUE TITLE
Synchronize wording and argument names in docs and examples

### ISSUE THREAD

**Issue by fjarri** [nucypher/rust-umbral#33]
Currently different terminology may be used in function argument names, comments and examples. Also the comments may be worded differently. Need to go through them and check.

In particular, we need to decide on the best name for the participating parties to use ("delegating/receiving" is good for the keys, but what would be the nouns for the parties, to use in function docstrings? Delegator/recipient?). "Alice" and "Bob" seem fine for the examples, but may be too specific to use in the API. 

Another possible source of confusion is `SecretKey` vs `PrivateKey`. The former is used by RustCrypto stack, so I copied that. But apparently it is not common terminology.

**Comment by fjarri** [comment]
Also apply here: field names of `Capsule`/`KeyFrag`/`CapsuleFrag` objects. It is probably worth making them match the notation of the [whitepaper](https://github.com/nucypher/umbral-doc/blob/master/umbral-doc.pdf)

Public API:

`Capsule`: 
`point_e` -> `e`
`point_v` -> `v`

`CapsuleFragProof`:
`point_e2` -> `e2`
`point_v2` -> `v2`
`kfrag_commitment` -> `u1`
`kfrag_pok` -> `u2`
`signature` -> `rho`

`CapsuleFrag`:
`point_e1` -> `e1`
`point_v1` -> `v1`

Names that are not exposed publicly may be changed as well, but the priority for that is lower.

**Comment by fjarri** [comment]
Note: since the fields above are not public anymore, these are not a high priority.

**Comment by cygnusv** [comment]
* "delegating/receiving and "Delegator/recipient" is perfectly consistent and understood
* SecretKey vs PrivateKey: I can live with `SecretKey`, specially if there's precedent in `RustCrypto`
* Field names: I don't think trying to be 100% consistent with the notation of the paper should be very important, as the paper and the code have different audiences and readability characteristics. While the short names are fine by me, this was an issue with a lot of debate back in the good ol' days and adding the "type" of the element as a prefix increased readability  with not much added cost.

**Comment by fjarri** [comment]
Current state: all the required changes were made in the API, need to review the docs to make sure everything is consistent. Bumping the milestone to v1.0
