### ISSUE TITLE
BITS conflict in bitvec/funty

### ISSUE THREAD

**Issue by ghardin1314** [nucypher/rust-umbral#34]
Build conflict caused by BITS being defined in both bitvec and funty. Can fix by specifying funty = "=1.1.0" as dependency. Will probably get fixed soon, but logging just in case.

https://github.com/bitvecto-rs/bitvec/issues/105

**Comment by fjarri** [comment]
For a little more context, the dependencies in question:
```
├── ecdsa v0.9.0
│   ├── elliptic-curve v0.7.1
│   │   ├── bitvec v0.18.4
│   │   │   ├── funty v1.0.1
```

`elliptic-curve` is in 0.9.x now, so perhaps updating it will resolve the problem.

**Comment by fjarri** [comment]
Looks like `funty=1.1.0` is loaded automatically now, I guess it can be safely closed.
