### ISSUE TITLE
Make it possible to use the package in React (specifically, in `create-react-app` projects)

### ISSUE THREAD

**Issue by fjarri** [nucypher/rust-umbral#49]
Apparently there are some problems with the loader not being able to load WASM files. We need to either solve it in this package (preferably), or provide a recipe for people who want to use it.

**Comment by gilles-hemmerle** [comment]
Hey guys!

Do you have any news regarding this issue? I'm currently stuck using this library in my react project.

**Comment by vepkenez** [comment]
> Hey guys!
> 
> Do you have any news regarding this issue? I'm currently stuck using this library in my react project.

You can try this [example I made](https://github.com/vepkenez/umbral-pre-react-example).  The important part is the craco config.  That might get you started.   We are working on packaging things up more neatly.

**Comment by piotr-roslaniec** [comment]
This issue might have been solved by #70

**Comment by fjarri** [comment]
Yes, seems to be. Closing.
