### ISSUE TITLE
Add a method to deserialize `SecretKeyFactory` from an externally created bytestring

### ISSUE THREAD

**Issue by fjarri** [nucypher/rust-umbral#57]
This is useful for the cases where one wants to derive `SecretKeyFactory` deterministically. One could use `from_bytes()` (because any 64 bytes will lead to a valid SKF), but it is better to make it a separate explicit method, to emphasize that the bytes did not come from an earlier SKF serialization. `SecretKeyFactory.from_secure_random_bytes()`? We will also need to expose the required bytestring length somehow.

**Comment by cygnusv** [comment]
In the context of umbral, 32 byte long input seeds are sufficient, assuming they have high entropy. What I'm not sure is how to support longer input seeds.

**Comment by fjarri** [comment]
For now we can limit the seeds to 32 bytes, possibly allowing larger seeds in the future - this won't break backward compatibility. For larger inputs, could we just use an HKDF?

One thing that I am not sure about: if we require high-entropy bytes (and pass them directly to the constructor), should we call it "seed"? To me, that implies that it can be something like a password, too. Should we emphasize the high-entropy requirement in the method name? Like `from_secure_random_bytes()` above, or something along these lines?
