### ISSUE TITLE
Add a method to produce a `SecretKeyFactory` from another factory deterministically.

### ISSUE THREAD

**Issue by fjarri** [nucypher/rust-umbral#59]
Should we do it just by label? Or label + salt, to add randomness?

**Comment by cygnusv** [comment]
My understanding of the SKF abstraction is that the seed input is assumed of high entropy. Therefore, salt shouldn't be necessary (or at most, optional).

**Comment by fjarri** [comment]
If it's not necessary, I'd rather not add an option if I can help it. 

As for the implementation, I suppose I'll go the same way as `secret_key_by_label()` currently works, except deriving however many bytes SKF needs - is that secure enough?
