### ISSUE TITLE
Re-evaluate encoding choice for human-readable formats.

### ISSUE THREAD

**Issue by fjarri** [nucypher/rust-umbral#95]
This issue also concerns `nucypher-core`.

Currently, when serializing to human-readable formats with `serde`, we are using hex encoding for anything under 33 bytes (that is, `PublicKey` in `umbral-pre`, and `Address`, `HRAC` and `FleetStateChecksum` in `nucypher-core`), and base64 for the rest. Is this a good choice? Other options:

- Use hex for everything, like, say, Ethereum RPC does. This will make the code simpler, but it will increase the size of serialized objects. Most of our objects are rather small, of the order of hundreds of bytes; the biggest offenders will be `EncryptedTreasureMap` and `MessageKit`, whose `ciphertext` fields can be large. 
- Use https://github.com/multiformats/multibase , and keep the current encoding scheme. This is more future-proof, and provides one entry point for encoding/decoding, but may be confusing for users.

**Comment by piotr-roslaniec** [comment]
My 2 cents:
* Just a note: If `rust-umbral` users consider the size of serialized objects too large, they may always re-serialize/compress them on the application level.
* `multibase` may add some complexity to how users consume serialization, but I would say that `rust-umbral` is such a low-level library that it makes this trade-off interesting. I.e this complexity is hidden from `nucypher-ts` users for example, and for someone implementing a higher-order primitive (like `nucypher-core`) it adds a lot of flexibility. Personally I would be in favor of that.
* Nothing wrong with serializing everything to hex, but I believe that (with some low probability) we will have to revisit this decision long down the road.

**Comment by fjarri** [comment]
I don't remember exactly, but I assume we did it in human readable formats mainly for the humans' benefit. It would be surprising to see a public key or an address in base64 in a JSON file.
